import pandas as pd
import os

# JSON data
json_data_toyota = [
  {
    "Make": "Toyota",
    "Model": "Aqua",
    "BaseModel": "Aqua",
    "Annual Petroleum Consumption For Fuel Type1": 8.5,
    "City Mpg For Fuel Type1": 53,
    "Co2 Tailpipe For Fuel Type1": 178,
    "Combined Mpg For Fuel Type1": 58,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 1900,
    "Highway Mpg For Fuel Type1": 62,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Hybrid",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Prius",
    "BaseModel": "Prius",
    "Annual Petroleum Consumption For Fuel Type1": 9.2,
    "City Mpg For Fuel Type1": 54,
    "Co2 Tailpipe For Fuel Type1": 192,
    "Combined Mpg For Fuel Type1": 56,
    "Cylinders": 4,
    "Engine displacement": 1.8,
    "Annual Fuel Cost For Fuel Type1": 2050,
    "Highway Mpg For Fuel Type1": 58,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Hybrid",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Midsize Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Axio",
    "BaseModel": "Axio",
    "Annual Petroleum Consumption For Fuel Type1": 10.8,
    "City Mpg For Fuel Type1": 30,
    "Co2 Tailpipe For Fuel Type1": 250,
    "Combined Mpg For Fuel Type1": 35,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2450,
    "Highway Mpg For Fuel Type1": 40,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2020,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Allion",
    "BaseModel": "Allion",
    "Annual Petroleum Consumption For Fuel Type1": 11.2,
    "City Mpg For Fuel Type1": 28,
    "Co2 Tailpipe For Fuel Type1": 270,
    "Combined Mpg For Fuel Type1": 32,
    "Cylinders": 4,
    "Engine displacement": 1.8,
    "Annual Fuel Cost For Fuel Type1": 2550,
    "Highway Mpg For Fuel Type1": 38,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Midsize Cars",
    "Year": 2019,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Premio",
    "BaseModel": "Premio",
    "Annual Petroleum Consumption For Fuel Type1": 11.5,
    "City Mpg For Fuel Type1": 27,
    "Co2 Tailpipe For Fuel Type1": 280,
    "Combined Mpg For Fuel Type1": 31,
    "Cylinders": 4,
    "Engine displacement": 1.8,
    "Annual Fuel Cost For Fuel Type1": 2600,
    "Highway Mpg For Fuel Type1": 37,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Midsize Cars",
    "Year": 2018,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Vitz",
    "BaseModel": "Vitz",
    "Annual Petroleum Consumption For Fuel Type1": 9.8,
    "City Mpg For Fuel Type1": 35,
    "Co2 Tailpipe For Fuel Type1": 220,
    "Combined Mpg For Fuel Type1": 40,
    "Cylinders": 3,
    "Engine displacement": 1.0,
    "Annual Fuel Cost For Fuel Type1": 2200,
    "Highway Mpg For Fuel Type1": 45,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Corolla",
    "BaseModel": "Corolla",
    "Annual Petroleum Consumption For Fuel Type1": 10.5,
    "City Mpg For Fuel Type1": 32,
    "Co2 Tailpipe For Fuel Type1": 240,
    "Combined Mpg For Fuel Type1": 36,
    "Cylinders": 4,
    "Engine displacement": 1.8,
    "Annual Fuel Cost For Fuel Type1": 2400,
    "Highway Mpg For Fuel Type1": 42,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2020,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Hilux",
    "BaseModel": "Hilux",
    "Annual Petroleum Consumption For Fuel Type1": 14.8,
    "City Mpg For Fuel Type1": 20,
    "Co2 Tailpipe For Fuel Type1": 450,
    "Combined Mpg For Fuel Type1": 23,
    "Cylinders": 4,
    "Engine displacement": 2.8,
    "Annual Fuel Cost For Fuel Type1": 3350,
    "Highway Mpg For Fuel Type1": 27,
    "Drive": "Rear-Wheel Drive",
    "Engine descriptor": "Turbo Diesel",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Manual 6-spd",
    "Vehicle Size Class": "Standard Pickup Trucks 2WD",
    "Year": 2021,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "Land Cruiser Prado",
    "BaseModel": "Prado",
    "Annual Petroleum Consumption For Fuel Type1": 16.5,
    "City Mpg For Fuel Type1": 18,
    "Co2 Tailpipe For Fuel Type1": 490,
    "Combined Mpg For Fuel Type1": 21,
    "Cylinders": 6,
    "Engine displacement": 3.5,
    "Annual Fuel Cost For Fuel Type1": 3750,
    "Highway Mpg For Fuel Type1": 25,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "V6",
    "Fuel Type": "Premium",
    "Fuel Type1": "Premium Gasoline",
    "Transmission": "Automatic (S6)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Toyota",
    "Model": "C-HR",
    "BaseModel": "C-HR LE",
    "Annual Petroleum Consumption For Fuel Type1": 10.5,
    "City Mpg For Fuel Type1": 27,
    "Co2 Tailpipe For Fuel Type1": 284,
    "Combined Mpg For Fuel Type1": 30,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 1400,
    "Highway Mpg For Fuel Type1": 31,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular Gasoline",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Subcompact Sport Utility Vehicle",
    "Year": 2023,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  }
]

json_data_nissan = [
  {
    "Make": "Nissan",
    "Model": "Sunny",
    "BaseModel": "Sunny",
    "Annual Petroleum Consumption For Fuel Type1": 11.2,
    "City Mpg For Fuel Type1": 28,
    "Co2 Tailpipe For Fuel Type1": 270,
    "Combined Mpg For Fuel Type1": 32,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2550,
    "Highway Mpg For Fuel Type1": 38,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2020,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Nissan",
    "Model": "Tiida",
    "BaseModel": "Tiida",
    "Annual Petroleum Consumption For Fuel Type1": 10.8,
    "City Mpg For Fuel Type1": 30,
    "Co2 Tailpipe For Fuel Type1": 250,
    "Combined Mpg For Fuel Type1": 35,
    "Cylinders": 4,
    "Engine displacement": 1.6,
    "Annual Fuel Cost For Fuel Type1": 2450,
    "Highway Mpg For Fuel Type1": 40,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2019,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Nissan",
    "Model": "X-Trail",
    "BaseModel": "X-Trail",
    "Annual Petroleum Consumption For Fuel Type1": 13.5,
    "City Mpg For Fuel Type1": 22,
    "Co2 Tailpipe For Fuel Type1": 320,
    "Combined Mpg For Fuel Type1": 26,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 3050,
    "Highway Mpg For Fuel Type1": 30,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Nissan",
    "Model": "Leaf",
    "BaseModel": "Leaf",
    "Annual Petroleum Consumption For Fuel Type1": 0,
    "City Mpg For Fuel Type1": 123,
    "Co2 Tailpipe For Fuel Type1": 0,
    "Combined Mpg For Fuel Type1": 112,
    "Cylinders": 0,
    "Engine displacement": 0,
    "Annual Fuel Cost For Fuel Type1": 600,
    "Highway Mpg For Fuel Type1": 101,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Electricity",
    "Fuel Type": "Electricity",
    "Fuel Type1": "Electricity",
    "Transmission": "Automatic (A1)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "Single-Speed",
    "Electric motor": "Yes",
    "Start-Stop": "N",
    "Rate": ""
  },
  {
    "Make": "Nissan",
    "Model": "March",
    "BaseModel": "March",
    "Annual Petroleum Consumption For Fuel Type1": 9.5,
    "City Mpg For Fuel Type1": 35,
    "Co2 Tailpipe For Fuel Type1": 220,
    "Combined Mpg For Fuel Type1": 40,
    "Cylinders": 3,
    "Engine displacement": 1.0,
    "Annual Fuel Cost For Fuel Type1": 2150,
    "Highway Mpg For Fuel Type1": 45,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  }
]

json_data_honda = [
  {
    "Make": "Honda",
    "Model": "Fit (Jazz)",
    "BaseModel": "Fit",
    "Annual Petroleum Consumption For Fuel Type1": 9.5,
    "City Mpg For Fuel Type1": 36,
    "Co2 Tailpipe For Fuel Type1": 210,
    "Combined Mpg For Fuel Type1": 40,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2150,
    "Highway Mpg For Fuel Type1": 44,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Hybrid",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "Yes",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Honda",
    "Model": "Vezel",
    "BaseModel": "Vezel",
    "Annual Petroleum Consumption For Fuel Type1": 10.5,
    "City Mpg For Fuel Type1": 30,
    "Co2 Tailpipe For Fuel Type1": 250,
    "Combined Mpg For Fuel Type1": 35,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2400,
    "Highway Mpg For Fuel Type1": 40,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Hybrid",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Small Sport Utility Vehicle 2WD",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "Yes",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Honda",
    "Model": "Grace",
    "BaseModel": "Grace",
    "Annual Petroleum Consumption For Fuel Type1": 9.8,
    "City Mpg For Fuel Type1": 34,
    "Co2 Tailpipe For Fuel Type1": 220,
    "Combined Mpg For Fuel Type1": 38,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2250,
    "Highway Mpg For Fuel Type1": 42,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Hybrid",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2020,
    "Transmission descriptor": "CVT",
    "Electric motor": "Yes",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Honda",
    "Model": "Civic",
    "BaseModel": "Civic",
    "Annual Petroleum Consumption For Fuel Type1": 11.2,
    "City Mpg For Fuel Type1": 30,
    "Co2 Tailpipe For Fuel Type1": 260,
    "Combined Mpg For Fuel Type1": 34,
    "Cylinders": 4,
    "Engine displacement": 1.8,
    "Annual Fuel Cost For Fuel Type1": 2550,
    "Highway Mpg For Fuel Type1": 38,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Honda",
    "Model": "CR-V",
    "BaseModel": "CR-V",
    "Annual Petroleum Consumption For Fuel Type1": 12.8,
    "City Mpg For Fuel Type1": 27,
    "Co2 Tailpipe For Fuel Type1": 300,
    "Combined Mpg For Fuel Type1": 31,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2900,
    "Highway Mpg For Fuel Type1": 34,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Honda",
    "Model": "Accord",
    "BaseModel": "Accord",
    "Annual Petroleum Consumption For Fuel Type1": 12.5,
    "City Mpg For Fuel Type1": 26,
    "Co2 Tailpipe For Fuel Type1": 290,
    "Combined Mpg For Fuel Type1": 30,
    "Cylinders": 4,
    "Engine displacement": 2.4,
    "Annual Fuel Cost For Fuel Type1": 2850,
    "Highway Mpg For Fuel Type1": 35,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Midsize Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  }
]

json_data_suzuki = [
  {
    "Make": "Suzuki",
    "Model": "Alto",
    "BaseModel": "Alto",
    "Annual Petroleum Consumption For Fuel Type1": 9.2,
    "City Mpg For Fuel Type1": 37,
    "Co2 Tailpipe For Fuel Type1": 200,
    "Combined Mpg For Fuel Type1": 42,
    "Cylinders": 3,
    "Engine displacement": 1.0,
    "Annual Fuel Cost For Fuel Type1": 2100,
    "Highway Mpg For Fuel Type1": 47,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Suzuki",
    "Model": "Wagon R",
    "BaseModel": "Wagon R",
    "Annual Petroleum Consumption For Fuel Type1": 9.5,
    "City Mpg For Fuel Type1": 35,
    "Co2 Tailpipe For Fuel Type1": 210,
    "Combined Mpg For Fuel Type1": 40,
    "Cylinders": 3,
    "Engine displacement": 1.0,
    "Annual Fuel Cost For Fuel Type1": 2150,
    "Highway Mpg For Fuel Type1": 45,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Suzuki",
    "Model": "Swift",
    "BaseModel": "Swift",
    "Annual Petroleum Consumption For Fuel Type1": 10.2,
    "City Mpg For Fuel Type1": 32,
    "Co2 Tailpipe For Fuel Type1": 230,
    "Combined Mpg For Fuel Type1": 36,
    "Cylinders": 4,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2300,
    "Highway Mpg For Fuel Type1": 40,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Suzuki",
    "Model": "Ciaz",
    "BaseModel": "Ciaz",
    "Annual Petroleum Consumption For Fuel Type1": 11.5,
    "City Mpg For Fuel Type1": 28,
    "Co2 Tailpipe For Fuel Type1": 260,
    "Combined Mpg For Fuel Type1": 32,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2600,
    "Highway Mpg For Fuel Type1": 37,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Midsize Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Suzuki",
    "Model": "Vitara",
    "BaseModel": "Vitara",
    "Annual Petroleum Consumption For Fuel Type1": 12.8,
    "City Mpg For Fuel Type1": 26,
    "Co2 Tailpipe For Fuel Type1": 300,
    "Combined Mpg For Fuel Type1": 30,
    "Cylinders": 4,
    "Engine displacement": 1.6,
    "Annual Fuel Cost For Fuel Type1": 2900,
    "Highway Mpg For Fuel Type1": 34,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Suzuki",
    "Model": "Jimny",
    "BaseModel": "Jimny",
    "Annual Petroleum Consumption For Fuel Type1": 13.5,
    "City Mpg For Fuel Type1": 24,
    "Co2 Tailpipe For Fuel Type1": 320,
    "Combined Mpg For Fuel Type1": 28,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 3050,
    "Highway Mpg For Fuel Type1": 32,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2021,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  }
]

json_data_mitsubishi = [
  {
    "Make": "Mitsubishi",
    "Model": "Mirage",
    "BaseModel": "Mirage",
    "Annual Petroleum Consumption For Fuel Type1": 9.5,
    "City Mpg For Fuel Type1": 36,
    "Co2 Tailpipe For Fuel Type1": 210,
    "Combined Mpg For Fuel Type1": 40,
    "Cylinders": 3,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2150,
    "Highway Mpg For Fuel Type1": 43,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mitsubishi",
    "Model": "Lancer",
    "BaseModel": "Lancer",
    "Annual Petroleum Consumption For Fuel Type1": 11.2,
    "City Mpg For Fuel Type1": 28,
    "Co2 Tailpipe For Fuel Type1": 260,
    "Combined Mpg For Fuel Type1": 32,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2550,
    "Highway Mpg For Fuel Type1": 37,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2021,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mitsubishi",
    "Model": "Outlander",
    "BaseModel": "Outlander",
    "Annual Petroleum Consumption For Fuel Type1": 13.5,
    "City Mpg For Fuel Type1": 24,
    "Co2 Tailpipe For Fuel Type1": 320,
    "Combined Mpg For Fuel Type1": 28,
    "Cylinders": 4,
    "Engine displacement": 2.4,
    "Annual Fuel Cost For Fuel Type1": 3050,
    "Highway Mpg For Fuel Type1": 32,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mitsubishi",
    "Model": "Montero Sport",
    "BaseModel": "Montero Sport",
    "Annual Petroleum Consumption For Fuel Type1": 14.8,
    "City Mpg For Fuel Type1": 20,
    "Co2 Tailpipe For Fuel Type1": 350,
    "Combined Mpg For Fuel Type1": 23,
    "Cylinders": 4,
    "Engine displacement": 2.4,
    "Annual Fuel Cost For Fuel Type1": 3350,
    "Highway Mpg For Fuel Type1": 27,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbo Diesel",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Automatic (S6)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2021,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  },
  {
    "Make": "Mitsubishi",
    "Model": "Pajero",
    "BaseModel": "Pajero",
    "Annual Petroleum Consumption For Fuel Type1": 16.5,
    "City Mpg For Fuel Type1": 18,
    "Co2 Tailpipe For Fuel Type1": 390,
    "Combined Mpg For Fuel Type1": 21,
    "Cylinders": 6,
    "Engine displacement": 3.2,
    "Annual Fuel Cost For Fuel Type1": 3750,
    "Highway Mpg For Fuel Type1": 25,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbo Diesel",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Automatic (S5)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2020,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  }
]

json_data_tata_mahindra = [
  {
    "Make": "Tata",
    "Model": "Nano",
    "BaseModel": "Nano",
    "Annual Petroleum Consumption For Fuel Type1": 9.0,
    "City Mpg For Fuel Type1": 40,
    "Co2 Tailpipe For Fuel Type1": 180,
    "Combined Mpg For Fuel Type1": 45,
    "Cylinders": 2,
    "Engine displacement": 0.6,
    "Annual Fuel Cost For Fuel Type1": 1800,
    "Highway Mpg For Fuel Type1": 50,
    "Drive": "Rear-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Manual (4-speed)",
    "Vehicle Size Class": "Mini Compact Car",
    "Year": 2018,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  },
  {
    "Make": "Tata",
    "Model": "Tiago",
    "BaseModel": "Tiago",
    "Annual Petroleum Consumption For Fuel Type1": 10.5,
    "City Mpg For Fuel Type1": 33,
    "Co2 Tailpipe For Fuel Type1": 210,
    "Combined Mpg For Fuel Type1": 36,
    "Cylinders": 3,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2200,
    "Highway Mpg For Fuel Type1": 39,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (AMT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2023,
    "Transmission descriptor": "AMT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Tata",
    "Model": "Tigor",
    "BaseModel": "Tigor",
    "Annual Petroleum Consumption For Fuel Type1": 11.0,
    "City Mpg For Fuel Type1": 30,
    "Co2 Tailpipe For Fuel Type1": 225,
    "Combined Mpg For Fuel Type1": 34,
    "Cylinders": 3,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2300,
    "Highway Mpg For Fuel Type1": 38,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (AMT)",
    "Vehicle Size Class": "Compact Sedans",
    "Year": 2023,
    "Transmission descriptor": "AMT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Tata",
    "Model": "Harrier",
    "BaseModel": "Harrier",
    "Annual Petroleum Consumption For Fuel Type1": 14.0,
    "City Mpg For Fuel Type1": 22,
    "Co2 Tailpipe For Fuel Type1": 340,
    "Combined Mpg For Fuel Type1": 26,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 3100,
    "Highway Mpg For Fuel Type1": 30,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Turbo Diesel",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2023,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mahindra",
    "Model": "KUV100",
    "BaseModel": "KUV100",
    "Annual Petroleum Consumption For Fuel Type1": 11.5,
    "City Mpg For Fuel Type1": 29,
    "Co2 Tailpipe For Fuel Type1": 240,
    "Combined Mpg For Fuel Type1": 32,
    "Cylinders": 3,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2500,
    "Highway Mpg For Fuel Type1": 35,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Compact SUV",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mahindra",
    "Model": "Scorpio",
    "BaseModel": "Scorpio",
    "Annual Petroleum Consumption For Fuel Type1": 16.2,
    "City Mpg For Fuel Type1": 18,
    "Co2 Tailpipe For Fuel Type1": 390,
    "Combined Mpg For Fuel Type1": 21,
    "Cylinders": 4,
    "Engine displacement": 2.2,
    "Annual Fuel Cost For Fuel Type1": 3700,
    "Highway Mpg For Fuel Type1": 25,
    "Drive": "Four-Wheel Drive",
    "Engine descriptor": "Turbo Diesel",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Manual (6-speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - 4WD",
    "Year": 2023,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  },
  {
    "Make": "Mahindra",
    "Model": "Thar",
    "BaseModel": "Thar",
    "Annual Petroleum Consumption For Fuel Type1": 17.8,
    "City Mpg For Fuel Type1": 16,
    "Co2 Tailpipe For Fuel Type1": 420,
    "Combined Mpg For Fuel Type1": 19,
    "Cylinders": 4,
    "Engine displacement": 2.2,
    "Annual Fuel Cost For Fuel Type1": 3900,
    "Highway Mpg For Fuel Type1": 22,
    "Drive": "Four-Wheel Drive",
    "Engine descriptor": "Turbo Diesel",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Off-Road SUV",
    "Year": 2023,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  }
]

json_data_mazda_subaru = [
  {
    "Make": "Mazda",
    "Model": "Demio",
    "BaseModel": "Demio",
    "Annual Petroleum Consumption For Fuel Type1": 10.5,
    "City Mpg For Fuel Type1": 30,
    "Co2 Tailpipe For Fuel Type1": 250,
    "Combined Mpg For Fuel Type1": 35,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2300,
    "Highway Mpg For Fuel Type1": 40,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mazda",
    "Model": "Axela",
    "BaseModel": "Axela",
    "Annual Petroleum Consumption For Fuel Type1": 11.0,
    "City Mpg For Fuel Type1": 28,
    "Co2 Tailpipe For Fuel Type1": 260,
    "Combined Mpg For Fuel Type1": 32,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2500,
    "Highway Mpg For Fuel Type1": 36,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mazda",
    "Model": "CX-5",
    "BaseModel": "CX-5",
    "Annual Petroleum Consumption For Fuel Type1": 12.5,
    "City Mpg For Fuel Type1": 26,
    "Co2 Tailpipe For Fuel Type1": 280,
    "Combined Mpg For Fuel Type1": 30,
    "Cylinders": 4,
    "Engine displacement": 2.5,
    "Annual Fuel Cost For Fuel Type1": 2700,
    "Highway Mpg For Fuel Type1": 34,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - AWD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Mazda",
    "Model": "BT-50",
    "BaseModel": "BT-50",
    "Annual Petroleum Consumption For Fuel Type1": 14.0,
    "City Mpg For Fuel Type1": 22,
    "Co2 Tailpipe For Fuel Type1": 320,
    "Combined Mpg For Fuel Type1": 25,
    "Cylinders": 4,
    "Engine displacement": 3.0,
    "Annual Fuel Cost For Fuel Type1": 3000,
    "Highway Mpg For Fuel Type1": 28,
    "Drive": "Four-Wheel Drive",
    "Engine descriptor": "Turbo Diesel",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Pickup Trucks",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "N",
    "Rate": ""
  },
  {
    "Make": "Subaru",
    "Model": "Impreza",
    "BaseModel": "Impreza",
    "Annual Petroleum Consumption For Fuel Type1": 11.5,
    "City Mpg For Fuel Type1": 27,
    "Co2 Tailpipe For Fuel Type1": 270,
    "Combined Mpg For Fuel Type1": 31,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2600,
    "Highway Mpg For Fuel Type1": 35,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated Boxer",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Subaru",
    "Model": "Forester",
    "BaseModel": "Forester",
    "Annual Petroleum Consumption For Fuel Type1": 12.0,
    "City Mpg For Fuel Type1": 26,
    "Co2 Tailpipe For Fuel Type1": 280,
    "Combined Mpg For Fuel Type1": 29,
    "Cylinders": 4,
    "Engine displacement": 2.5,
    "Annual Fuel Cost For Fuel Type1": 2700,
    "Highway Mpg For Fuel Type1": 33,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated Boxer",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Sport Utility Vehicle - AWD",
    "Year": 2025,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Subaru",
    "Model": "XV",
    "BaseModel": "XV",
    "Annual Petroleum Consumption For Fuel Type1": 11.0,
    "City Mpg For Fuel Type1": 27,
    "Co2 Tailpipe For Fuel Type1": 260,
    "Combined Mpg For Fuel Type1": 31,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2500,
    "Highway Mpg For Fuel Type1": 34,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated Boxer",
    "Fuel Type": "Regular",
    "Fuel Type1": "Regular Gasoline",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Subcompact SUV",
    "Year": 2023,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  }
]

json_data_maruti_suzuki = [
  {
    "Make": "Maruti Suzuki",
    "Model": "Alto",
    "BaseModel": "Alto",
    "Annual Petroleum Consumption For Fuel Type1": 7.5,
    "City Mpg For Fuel Type1": 22,
    "Co2 Tailpipe For Fuel Type1": 170,
    "Combined Mpg For Fuel Type1": 25,
    "Cylinders": 3,
    "Engine displacement": 0.8,
    "Annual Fuel Cost For Fuel Type1": 1800,
    "Highway Mpg For Fuel Type1": 28,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Maruti Suzuki",
    "Model": "Swift",
    "BaseModel": "Swift",
    "Annual Petroleum Consumption For Fuel Type1": 9.2,
    "City Mpg For Fuel Type1": 20,
    "Co2 Tailpipe For Fuel Type1": 190,
    "Combined Mpg For Fuel Type1": 23,
    "Cylinders": 4,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2100,
    "Highway Mpg For Fuel Type1": 26,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Maruti Suzuki",
    "Model": "Baleno",
    "BaseModel": "Baleno",
    "Annual Petroleum Consumption For Fuel Type1": 10.0,
    "City Mpg For Fuel Type1": 18,
    "Co2 Tailpipe For Fuel Type1": 200,
    "Combined Mpg For Fuel Type1": 22,
    "Cylinders": 4,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2300,
    "Highway Mpg For Fuel Type1": 25,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (CVT)",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "CVT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Maruti Suzuki",
    "Model": "Dzire",
    "BaseModel": "Dzire",
    "Annual Petroleum Consumption For Fuel Type1": 9.0,
    "City Mpg For Fuel Type1": 21,
    "Co2 Tailpipe For Fuel Type1": 180,
    "Combined Mpg For Fuel Type1": 24,
    "Cylinders": 4,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2200,
    "Highway Mpg For Fuel Type1": 27,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (AMT)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "AMT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  }
]

json_data_hyundai = [
  {
    "Make": "Hyundai",
    "Model": "i10",
    "BaseModel": "i10",
    "Annual Petroleum Consumption For Fuel Type1": 7.5,
    "City Mpg For Fuel Type1": 18,
    "Co2 Tailpipe For Fuel Type1": 160,
    "Combined Mpg For Fuel Type1": 20,
    "Cylinders": 3,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 1900,
    "Highway Mpg For Fuel Type1": 22,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Hyundai",
    "Model": "Grand i10",
    "BaseModel": "Grand i10",
    "Annual Petroleum Consumption For Fuel Type1": 8.0,
    "City Mpg For Fuel Type1": 19,
    "Co2 Tailpipe For Fuel Type1": 170,
    "Combined Mpg For Fuel Type1": 21,
    "Cylinders": 4,
    "Engine displacement": 1.2,
    "Annual Fuel Cost For Fuel Type1": 2100,
    "Highway Mpg For Fuel Type1": 24,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (AMT)",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "AMT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Hyundai",
    "Model": "Creta",
    "BaseModel": "Creta",
    "Annual Petroleum Consumption For Fuel Type1": 11.5,
    "City Mpg For Fuel Type1": 15,
    "Co2 Tailpipe For Fuel Type1": 200,
    "Combined Mpg For Fuel Type1": 18,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2500,
    "Highway Mpg For Fuel Type1": 20,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Diesel",
    "Fuel Type1": "Diesel",
    "Transmission": "Automatic (DCT)",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "DCT",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  }
]

json_data_korean_hyundai_kia = [
  {
    "Make": "Hyundai",
    "Model": "Tucson",
    "BaseModel": "Tucson",
    "Annual Petroleum Consumption For Fuel Type1": 13.0,
    "City Mpg For Fuel Type1": 12,
    "Co2 Tailpipe For Fuel Type1": 230,
    "Combined Mpg For Fuel Type1": 15,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2800,
    "Highway Mpg For Fuel Type1": 18,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Standard Sport Utility Vehicle 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Hyundai",
    "Model": "Santa Fe",
    "BaseModel": "Santa Fe",
    "Annual Petroleum Consumption For Fuel Type1": 14.5,
    "City Mpg For Fuel Type1": 11,
    "Co2 Tailpipe For Fuel Type1": 250,
    "Combined Mpg For Fuel Type1": 14,
    "Cylinders": 4,
    "Engine displacement": 2.4,
    "Annual Fuel Cost For Fuel Type1": 3100,
    "Highway Mpg For Fuel Type1": 17,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (8-speed)",
    "Vehicle Size Class": "Standard Sport Utility Vehicle 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Hyundai",
    "Model": "Elantra",
    "BaseModel": "Elantra",
    "Annual Petroleum Consumption For Fuel Type1": 7.0,
    "City Mpg For Fuel Type1": 16,
    "Co2 Tailpipe For Fuel Type1": 170,
    "Combined Mpg For Fuel Type1": 18,
    "Cylinders": 4,
    "Engine displacement": 1.6,
    "Annual Fuel Cost For Fuel Type1": 1600,
    "Highway Mpg For Fuel Type1": 20,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual (6-speed)",
    "Vehicle Size Class": "Compact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Hyundai",
    "Model": "Accent",
    "BaseModel": "Accent",
    "Annual Petroleum Consumption For Fuel Type1": 6.5,
    "City Mpg For Fuel Type1": 18,
    "Co2 Tailpipe For Fuel Type1": 160,
    "Combined Mpg For Fuel Type1": 20,
    "Cylinders": 4,
    "Engine displacement": 1.6,
    "Annual Fuel Cost For Fuel Type1": 1500,
    "Highway Mpg For Fuel Type1": 21,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Kia",
    "Model": "Sportage",
    "BaseModel": "Sportage",
    "Annual Petroleum Consumption For Fuel Type1": 12.5,
    "City Mpg For Fuel Type1": 13,
    "Co2 Tailpipe For Fuel Type1": 220,
    "Combined Mpg For Fuel Type1": 16,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2700,
    "Highway Mpg For Fuel Type1": 19,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Kia",
    "Model": "Seltos",
    "BaseModel": "Seltos",
    "Annual Petroleum Consumption For Fuel Type1": 11.0,
    "City Mpg For Fuel Type1": 14,
    "Co2 Tailpipe For Fuel Type1": 210,
    "Combined Mpg For Fuel Type1": 17,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2600,
    "Highway Mpg For Fuel Type1": 19,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Kia",
    "Model": "Picanto",
    "BaseModel": "Picanto",
    "Annual Petroleum Consumption For Fuel Type1": 5.0,
    "City Mpg For Fuel Type1": 20,
    "Co2 Tailpipe For Fuel Type1": 140,
    "Combined Mpg For Fuel Type1": 22,
    "Cylinders": 4,
    "Engine displacement": 1.0,
    "Annual Fuel Cost For Fuel Type1": 1300,
    "Highway Mpg For Fuel Type1": 25,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Kia",
    "Model": "Rio",
    "BaseModel": "Rio",
    "Annual Petroleum Consumption For Fuel Type1": 6.5,
    "City Mpg For Fuel Type1": 17,
    "Co2 Tailpipe For Fuel Type1": 150,
    "Combined Mpg For Fuel Type1": 19,
    "Cylinders": 4,
    "Engine displacement": 1.4,
    "Annual Fuel Cost For Fuel Type1": 1500,
    "Highway Mpg For Fuel Type1": 22,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  }
]

json_data_chinese_cars = [
  {
    "Make": "BYD",
    "Model": "Atto 3",
    "BaseModel": "Atto 3",
    "Annual Petroleum Consumption For Fuel Type1": 0,
    "City Mpg For Fuel Type1": "",
    "Co2 Tailpipe For Fuel Type1": 0,
    "Combined Mpg For Fuel Type1": "",
    "Cylinders": "",
    "Engine displacement": 0,
    "Annual Fuel Cost For Fuel Type1": 800,
    "Highway Mpg For Fuel Type1": "",
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Electricity",
    "Fuel Type": "Electricity",
    "Fuel Type1": "Electricity",
    "Transmission": "Automatic (Single Speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "Dual Electric Motors",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "BYD",
    "Model": "Han",
    "BaseModel": "Han",
    "Annual Petroleum Consumption For Fuel Type1": 0,
    "City Mpg For Fuel Type1": "",
    "Co2 Tailpipe For Fuel Type1": 0,
    "Combined Mpg For Fuel Type1": "",
    "Cylinders": "",
    "Engine displacement": 0,
    "Annual Fuel Cost For Fuel Type1": 900,
    "Highway Mpg For Fuel Type1": "",
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Electricity",
    "Fuel Type": "Electricity",
    "Fuel Type1": "Electricity",
    "Transmission": "Automatic (Single Speed)",
    "Vehicle Size Class": "Full-Size Sedans",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "Dual Electric Motors",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "MG",
    "Model": "ZS",
    "BaseModel": "ZS",
    "Annual Petroleum Consumption For Fuel Type1": 7.5,
    "City Mpg For Fuel Type1": 15,
    "Co2 Tailpipe For Fuel Type1": 180,
    "Combined Mpg For Fuel Type1": 17,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 1500,
    "Highway Mpg For Fuel Type1": 20,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "MG",
    "Model": "HS",
    "BaseModel": "HS",
    "Annual Petroleum Consumption For Fuel Type1": 9.5,
    "City Mpg For Fuel Type1": 12,
    "Co2 Tailpipe For Fuel Type1": 230,
    "Combined Mpg For Fuel Type1": 14,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2000,
    "Highway Mpg For Fuel Type1": 16,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (7-speed)",
    "Vehicle Size Class": "Standard Sport Utility Vehicle 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "MG",
    "Model": "5",
    "BaseModel": "5",
    "Annual Petroleum Consumption For Fuel Type1": 7.0,
    "City Mpg For Fuel Type1": 16,
    "Co2 Tailpipe For Fuel Type1": 170,
    "Combined Mpg For Fuel Type1": 18,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 1400,
    "Highway Mpg For Fuel Type1": 20,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (6-speed)",
    "Vehicle Size Class": "Compact Sedans",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Chery",
    "Model": "Tiggo",
    "BaseModel": "Tiggo",
    "Annual Petroleum Consumption For Fuel Type1": 8.0,
    "City Mpg For Fuel Type1": 14,
    "Co2 Tailpipe For Fuel Type1": 210,
    "Combined Mpg For Fuel Type1": 16,
    "Cylinders": 4,
    "Engine displacement": 1.6,
    "Annual Fuel Cost For Fuel Type1": 1600,
    "Highway Mpg For Fuel Type1": 19,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Chery",
    "Model": "QQ",
    "BaseModel": "QQ",
    "Annual Petroleum Consumption For Fuel Type1": 5.0,
    "City Mpg For Fuel Type1": 20,
    "Co2 Tailpipe For Fuel Type1": 140,
    "Combined Mpg For Fuel Type1": 22,
    "Cylinders": 4,
    "Engine displacement": 1.0,
    "Annual Fuel Cost For Fuel Type1": 1200,
    "Highway Mpg For Fuel Type1": 25,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Haval",
    "Model": "H6",
    "BaseModel": "H6",
    "Annual Petroleum Consumption For Fuel Type1": 10.0,
    "City Mpg For Fuel Type1": 13,
    "Co2 Tailpipe For Fuel Type1": 200,
    "Combined Mpg For Fuel Type1": 15,
    "Cylinders": 4,
    "Engine displacement": 2.0,
    "Annual Fuel Cost For Fuel Type1": 2100,
    "Highway Mpg For Fuel Type1": 18,
    "Drive": "All-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (7-speed)",
    "Vehicle Size Class": "Standard Sport Utility Vehicle 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Haval",
    "Model": "Jolion",
    "BaseModel": "Jolion",
    "Annual Petroleum Consumption For Fuel Type1": 9.0,
    "City Mpg For Fuel Type1": 15,
    "Co2 Tailpipe For Fuel Type1": 190,
    "Combined Mpg For Fuel Type1": 17,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 2000,
    "Highway Mpg For Fuel Type1": 20,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Turbocharged",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Automatic (7-speed)",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "Automatic",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Changan",
    "Model": "CS35",
    "BaseModel": "CS35",
    "Annual Petroleum Consumption For Fuel Type1": 8.5,
    "City Mpg For Fuel Type1": 14,
    "Co2 Tailpipe For Fuel Type1": 210,
    "Combined Mpg For Fuel Type1": 16,
    "Cylinders": 4,
    "Engine displacement": 1.6,
    "Annual Fuel Cost For Fuel Type1": 1700,
    "Highway Mpg For Fuel Type1": 19,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Sport Utility Vehicle - 2WD",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  },
  {
    "Make": "Changan",
    "Model": "Alsvin",
    "BaseModel": "Alsvin",
    "Annual Petroleum Consumption For Fuel Type1": 7.0,
    "City Mpg For Fuel Type1": 15,
    "Co2 Tailpipe For Fuel Type1": 180,
    "Combined Mpg For Fuel Type1": 17,
    "Cylinders": 4,
    "Engine displacement": 1.5,
    "Annual Fuel Cost For Fuel Type1": 1400,
    "Highway Mpg For Fuel Type1": 20,
    "Drive": "Front-Wheel Drive",
    "Engine descriptor": "Naturally Aspirated",
    "Fuel Type": "Petrol",
    "Fuel Type1": "Petrol",
    "Transmission": "Manual 5-spd",
    "Vehicle Size Class": "Subcompact Cars",
    "Year": 2022,
    "Transmission descriptor": "Manual",
    "Electric motor": "",
    "Start-Stop": "Y",
    "Rate": ""
  }
]

# Convert JSON to DataFrame

# List of your JSON data sets and their corresponding names
json_data_sets = [
    ("json_data_toyota", json_data_toyota),
    ("json_data_nissan", json_data_nissan),
    ("json_data_honda", json_data_honda),
    ("json_data_suzuki", json_data_suzuki),
    ("json_data_mitsubishi", json_data_mitsubishi),
    ("json_data_tata_mahindra", json_data_tata_mahindra),
    ("json_data_mazda_subaru", json_data_mazda_subaru),
    ("json_data_maruti_suzuki", json_data_maruti_suzuki),
    ("json_data_hyundai", json_data_hyundai),
    ("json_data_korean_hyundai_kia", json_data_korean_hyundai_kia),
    ("json_data_chinese_cars", json_data_chinese_cars)
]  # Add more datasets as needed

# Load existing CSV file
csv_file = "all-vehicles-model-formatted.csv"  # Change this to your actual CSV file path

# Initialize an empty DataFrame or load an existing CSV file
df_existing = pd.read_csv(csv_file) if os.path.exists(csv_file) else pd.DataFrame()

# Loop through each json_data set, convert to DataFrame, and append to the existing DataFrame
for name, json_data in json_data_sets:
    df_new = pd.DataFrame(json_data)
    df_existing = pd.concat([df_existing, df_new], ignore_index=True)
    print(f"Added {name}...")  # Print the name of the dataset

# Specify the new file path to save both existing and new data
new_csv_file = "updated_data_set.csv"

# Save the updated DataFrame back to the new CSV file
df_existing.to_csv(new_csv_file, index=False)

print("CSV file updated and saved successfully to", new_csv_file)
